#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x421E6472811F9A81 (infra-root@openstack.org)
#
Name     : python-designateclient
Version  : 2.9.0
Release  : 27
URL      : http://tarballs.openstack.org/python-designateclient/python-designateclient-2.9.0.tar.gz
Source0  : http://tarballs.openstack.org/python-designateclient/python-designateclient-2.9.0.tar.gz
Source99 : http://tarballs.openstack.org/python-designateclient/python-designateclient-2.9.0.tar.gz.asc
Summary  : OpenStack DNS-as-a-Service - Client
Group    : Development/Tools
License  : Apache-2.0
Requires: python-designateclient-bin
Requires: python-designateclient-python3
Requires: python-designateclient-license
Requires: python-designateclient-python
Requires: Sphinx
Requires: cliff
Requires: debtcollector
Requires: jsonschema
Requires: keystoneauth1
Requires: openstackdocstheme
Requires: osc-lib
Requires: oslo.utils
Requires: pbr
Requires: requests
Requires: six
Requires: stevedore
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Team and repository tags
        ========================

%package bin
Summary: bin components for the python-designateclient package.
Group: Binaries
Requires: python-designateclient-license

%description bin
bin components for the python-designateclient package.


%package license
Summary: license components for the python-designateclient package.
Group: Default

%description license
license components for the python-designateclient package.


%package python
Summary: python components for the python-designateclient package.
Group: Default
Requires: python-designateclient-python3

%description python
python components for the python-designateclient package.


%package python3
Summary: python3 components for the python-designateclient package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-designateclient package.


%prep
%setup -q -n python-designateclient-2.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532381536
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/python-designateclient
cp LICENSE %{buildroot}/usr/share/doc/python-designateclient/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/designate

%files license
%defattr(-,root,root,-)
/usr/share/doc/python-designateclient/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
